### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Tezcatlipoca22** [LouisAsanaka/Valorant-Zone-Stats#8]
Hello,

Is linux supported for this version ?

**Comment by LouisAsanaka** [comment]
Hi, Linux is currently not supported. The main reason is the lack of username/password authentication, which I didn't really think should be a thing for a program like this, especially since VALORANT is a Windows-exclusive game. The program currently authenticates with the Riot Client's logged-in credentials, which does not give the program access to the user's password in any way. The program should definitely be able to run on Linux otherwise (other than some Windows paths being used afaik).

However, if I ever get around to making a web version of this, username/password authentication would be necessary, which would mean cross-platform support.

Hope this answers your question!

**Comment by LouisAsanaka** [comment]
> Hey,
> 
> Thank you for your reply, I asked the question because I want to develop a web app that looks like yours but I want to host it on a linux server.
> 
> But thanks anyways,

It shouldn't be that hard to implement password authentication (something like [this](https://gist.github.com/Luc1412/1f93257a2a808679ff014f258db6c35b)). There are actually more resources on that then cookie authentication.
